[package]
name = "selection_list"
description = "A library for selection lists"
license = "AGPL-3.0-or-later"
edition = "2024"

[dependencies]
bevy = { workspace = true }
hud = { workspace = true }
keyboard = { workspace = true }
manual = { workspace = true }
strum = { workspace = true }
util = { workspace = true }

[lints]
workspace = true
